name: espace_famille
description: "Application permettant de connecter les membre d'une famille"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_rating_stars: ^1.1.0
  palette_generator: ^0.3.3+4
  image_picker: ^1.0.8
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.5
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  intl: 0.19.0
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.3.10
  firebase_storage: ^12.4.4

flutter_native_splash:
  color: "#04898A"  # Couleur de fond
  image: assets/images/splash.png  # Image du splash screen
  android: true
  ios: true
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/cat_profile_img.jpg
    - assets/images/naruto.jpg
    - assets/images/bird.png
    - assets/images/face_male.png
    - assets/images/smiley_laughing.png
    - assets/images/task_list.png
    - assets/images/horaire.jpg
    - assets/images/google_image_logo.png
    - assets/images/trophy_icon.png
    - assets/images/task_icon.png
    - assets/images/family_jump.jpg
    - assets/images/splash.png
    - assets/images/default_profile_pictures/1.jpg
    - assets/images/default_profile_pictures/2.jpg
    - assets/images/default_profile_pictures/3.jpg
    - assets/images/default_profile_pictures/4.jpg
    - assets/images/default_profile_pictures/5.jpg
flutter_intl:
  enabled: true