name: espace_famille
description: "Application permettant de connecter les membre d'une famille"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_rating_stars: ^1.1.0
  palette_generator: ^0.3.3+4
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cat_profile_img.jpg
    - assets/images/naruto.jpg
    - assets/images/bird.png
    - assets/images/face_male.png
    - assets/images/smiley_laughing.png
    - assets/images/task_list.png