// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmpM__aS52kS7l0kXm0-VoZtnGfNt3DJY',
    appId: '1:646552966394:web:f2ffa15b643a7243886543',
    messagingSenderId: '646552966394',
    projectId: 'espace-famille',
    authDomain: 'espace-famille.firebaseapp.com',
    storageBucket: 'espace-famille.firebasestorage.app',
    measurementId: 'G-MXB4XJXX3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAca0lcUfIn1a1TbfM0HEABw8e7pkfze_o',
    appId: '1:646552966394:android:cf289f99dc39c538886543',
    messagingSenderId: '646552966394',
    projectId: 'espace-famille',
    storageBucket: 'espace-famille.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NAt1LU1nwHvmem9m3obOCrUbeMk6cOE',
    appId: '1:646552966394:ios:4c14934366b5d761886543',
    messagingSenderId: '646552966394',
    projectId: 'espace-famille',
    storageBucket: 'espace-famille.firebasestorage.app',
    iosBundleId: 'com.example.espaceFamille',
  );

}